geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('profile/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='list'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
]

geekshop/geekshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainapp import urls
from . import settings
from .views import contacts, main

app_name = 'geekshop'

urlpatterns = [
    path('', main, name='index'),
    path('admin/', admin.site.urls),
    path('contacts/', contacts, name='contacts'),
    path('products/', include(urls, namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from .views import products

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
]

geekshop/geekshop/views.py
from django.shortcuts import render

from basketapp.models import Basket
from mainapp.models import Product, ProductCategory


def main(request):
    products = Product.objects.all()[:4]
    basket = ''

    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    context = {
        'slogan': 'Супер УДОБНЫЕ СТУЛЬЯ',
        'topic': 'Тренды',
        'products': products,
        'basket': basket,
    }
    return render(request, 'index.html', context=context)


def contacts(request):
    return render(request, 'contact.html')

geekshop/geekshop/templates/includes/inc_main_menu.html
<div class="header clearfix">
    <a href="{% url 'index' %}" class="logo"></a>
    <ul class="menu">
        <li><a href="{% url 'index' %}" class="{% if request.resolver_match.route == '' %}
                    active
                  {% endif %}">домой</a></li>
        <li><a href="{% url 'products:category' 0 %}" class="{% if request.resolver_match.route == 'products/' %}
                        active
                      {% endif %}">продукты</a></li>
        <li><a href="{% url 'contacts' %}" class="{% if request.resolver_match.route == 'contacts/' %}
                        active
                      {% endif %}">контакты</a></li>
        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'auth:edit' %}">
                    {{ user.first_name|default:'Пользователь' }}
                </a>
            </li>
        {% endif %}
            <li>
                {% if user.is_authenticated %}
                  <a href="{% url 'auth:logout' %}">выйти</a>
                {% else %}
                  <a href="{% url 'auth:login' %}">войти</a>
                {% endif %}
            </li>
    </ul>
    {% if basket %}
        <a href="{% url 'basket:list' %}" class="fa fa-shopping-basket">
            <span>
                {% if basket %} {{ basket|length }} {% endif %}
            </span>
        </a>
    {% endif %}
    <a href="#" class="search"></a>

</div>