geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('profile/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='list'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
]

geekshop/geekshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainapp import urls
from . import settings
from .views import contacts, main

app_name = 'geekshop'

urlpatterns = [
    path('', main, name='index'),
    path('admin/', admin.site.urls),
    path('contacts/', contacts, name='contacts'),
    path('products/', include(urls, namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from .views import products

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='имя')

    description = models.TextField(
        verbose_name='описание',
        blank=True
    )

    created = models.DateTimeField(
        auto_now_add=True
    )
    updated = models.DateTimeField(
        auto_now=True
    )

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        verbose_name='категория',
    )

    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128,
    )

    image = models.ImageField(
        upload_to='products_img',
        blank=True,
    )

    short_desc = models.CharField(
        max_length=256,
        verbose_name='краткое описание',
        blank=True,
    )

    description = models.TextField(
        verbose_name='описание продукта',
        blank=True,
        max_length=500
    )

    price = models.DecimalField(
        verbose_name='цена продукта',
        max_digits=8,
        decimal_places=2,
        default=0,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0
    )

    def __str__(self):
        return f"{self.name} ({self.category.name})"

geekshop/mainapp/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from mainapp.models import ProductCategory, Product


def products(request, pk=None):
    print(pk)
    title = 'продукты'

    categories = ProductCategory.objects.all()
    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by('price')
            category = {'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category_id__pk=pk).order_by('price')

    context = {
        'title': title,
        'categories': categories,
        'category': category,
        'products': products,
    }
    return render(request, 'products_list.html', context=context)

geekshop/mainapp/templates/inc_categories_menu.html
<ul class="links-menu">
    <li>
        <a href="{% url 'products:category' 0 %}"
           class="{% if request.resolver_match.kwargs.pk == '0' %}
                    active
                  {% endif %}">
            все
        </a>

    </li>
    {% for link in categories %}
        <li>
            <a href="{% url 'products:category' link.pk %}"
               class="{% if request.resolver_match.kwargs.pk == link.pk %}
                        active
                      {% endif %}">
                {{ link.name }}
            </a>
        </li>
    {% endfor %}
</ul>

geekshop/mainapp/templates/products.html
{% extends 'base.html' %}

{% load static %}

{% block main_slider %}
	<div class="container">
		<div class="hero-white">
            {% include 'includes/inc_main_menu.html' %}
		</div>
{% endblock %}
{% block content %}
		<div class="details">
			<div class="links clearfix">
                {% include 'inc_categories_menu.html' %}
			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="/static/img/slider1.jpg">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="/static/img/controll.jpg" class="block-text-img" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="/static/img/controll1.jpg" class="block-text-img" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="/static/img/controll2.jpg" class="block-text-img" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">Отличный стул</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> 2585.9 <span>руб</span></p>
					<a href="#" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						<p>Расположитесь комфортно.</p> 
						<p>Отличное качество материалов
						позволит вам это.</p> 
						<p>Различные цвета</p>
						<p>высочайший уровень
						эргономики и прочность.</p>
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="/static/img/product-11.jpg" alt="">
							<div class="text">
								<img src="/static/img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/static/img/product-21.jpg" alt="">
							<div class="text">
								<img src="/static/img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/static/img/product-31.jpg" alt="">
							<div class="text">
								<img src="/static/img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>

				</div>
			</div>
		</div>


{% endblock %}

geekshop/mainapp/templates/products_list.html
{% extends 'base.html' %}

{% load static %}

{% block main_slider %}
	<div class="container">
		<div class="hero-white">
			{% include 'includes/inc_main_menu.html' %}
		</div>
{% endblock %}
{% block content %}
		<div class="details">
			<div class="links clearfix">
                {% include 'inc_categories_menu.html' %}
			</div>
            <h2>
                Категория: {{ category.name }}
            </h2>
            <div class="category-products row">
              {% for product in products %}
                <div class="block w-25 my-3 mx-3">
                  <a href="{% url 'basket:add' product.pk %}">
                    <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                    <div class="text">
                      <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                      <h4>{{ product.name }}</h4>
                      <p>{{ product.description }} </p>
                    </div>
                  </a>
                </div>
              {% endfor %}
            </div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="/static/img/product-11.jpg" alt="">
							<div class="text">
								<img src="/static/img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/static/img/product-21.jpg" alt="">
							<div class="text">
								<img src="/static/img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/static/img/product-31.jpg" alt="">
							<div class="text">
								<img src="/static/img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>

				</div>
			</div>
		</div>


{% endblock %}